### ISSUE TITLE
"node-gyp: Permission denied" when installing as root

### ISSUE THREAD

**Issue by hansjd** [Daplie/letsencrypt-cli#5] opened 2016-02-09 09:53 UTC
when doing
```
# npm install -g letsencrypt-cli
```
I get the error
```
/root/.nvm/versions/node/v5.0.0/bin/letsencrypt -> /root/.nvm/versions/node/v5.0.0/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js
/root/.nvm/versions/node/v5.0.0/bin/letsencrypt-node -> /root/.nvm/versions/node/v5.0.0/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js

> ursa@0.9.1 install /root/.nvm/versions/node/v5.0.0/lib/node_modules/letsencrypt-cli/node_modules/ursa
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "/root/.nvm/versions/node/v5.0.0/bin/node" "/root/.nvm/versions/node/v5.0.0/bin/npm" "install" "-g" "letsencrypt-cli"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ursa@0.9.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ursa@0.9.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

found this solution to work when trying to install as root (not sudo)
```
# npm config set unsafe-perm true
```
maybe not best solution, but it works

**Comment by coolaj86** [comment] 2016-02-22 16:34
There is no reason to run this as root that I am aware of. It isn't the intended behavior and it is advised against in the npm manual.

I don't believe this has anything to do with `letsencrypt-cli` (in fact the `ursa` package is the one throwing the error), but rather the problem you are experiencing is most likely a very common one as a result of mixing sometimes using `sudo npm` and other times not.

I would recommend you `rm -rf ~/.npm` and not use `sudo` and not run `npm` as root.

I'm closing the issue but I'm open to discussing it further.

**Closed by coolaj86** 2016-02-22 16:34 UTC
