### ISSUE TITLE
Exception when trying to enroll

### ISSUE THREAD

**Issue by rmhrisk** [Daplie/letsencrypt-cli#1] opened 2015-12-26 03:07 UTC
STICKY
======

This issue happens with renewals and is actually dependent on https://github.com/Daplie/node-letsencrypt/issues/23 Track activity there.

Workaround
-----------------

Remove the accounts and renewals folders.

```bash
rm -r ~/letsencrypt/etc/renewal/
rm -r ~/letsencrypt/etc/accounts/
```

Note that there is a rate limit on how many accounts you can create per week, so don't just do this willy nilly if you have a large number of sites.

Original Issue
==========

```
root@host:~# sudo letsencrypt certonly   --agree-tos --email email@example.com   --webroot --webroot-path /usr/share/nginx/host.example.com    --config-dir /etc/letsencrypt    --domains host.example.com    --server https://acme-v01.api.letsencrypt.org/director
```

results in
```
[Error]: letsencrypt-cli
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at b64ToBinstr (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/lib/accounts.js:109:21
    at tryCatcher (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:615:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:143:14)
```

**Comment by coolaj86** [comment] 2015-12-26 11:41
I've seen this problem before and I thought I had fixed it. Which version of node are you running?

```bash
node --version
```

And it looks like you're on a OS X / Linux / BSD/ *nix type system, so I don't know why `urrsa` didn't install for you (it's falling back to forge).

The easiest solution is probably to make sure that you've got node 5.x installed and that `ursa` compiled properly.

```bash
curl -fsSL bit.ly/iojs-dev -o /tmp/iojs-dev.sh; bash /tmp/iojs-dev.sh

npm install -g letsencrypt-cli@latest
```

I don't have time to fix it right now (about to begin an all-day trip with family), but I will take a look either tonight or Monday.

The problem is that right here the wrong type of data (one of BigInteger, Buffer, String) is being passed.
<https://github.com/Daplie/letiny-core/blob/master/lib/letsencrypt-forge-extra.js#L19>

```
    at b64ToBinstr (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:45:5)
```

**Comment by coolaj86** [comment] 2015-12-26 11:43
Also note that `--server https://acme-v01.api.letsencrypt.org/director` should be `--server https://acme-v01.api.letsencrypt.org/directory` (was missing the `y` at the end).

**Comment by coolaj86** [comment] 2015-12-28 17:03
bump. Can you tell me your node version?

**Comment by rmhrisk** [comment] 2015-12-28 21:20
I am using node v5.3.0 on 3.13.0-58-generic #97-Ubuntu SMP. I will check if your steps work.

**Comment by rmhrisk** [comment] 2015-12-28 21:21
As for use of forge, here is one of my libraries : https://pkijs.org which may be a viable alternaitve for you.

**Comment by rmhrisk** [comment] 2015-12-28 21:23
Nope, same:

**Comment by coolaj86** [comment] 2016-01-01 22:28
Just wanted to let you know that I haven't forgotten about this. I do want to investigate, just got a little bit of a backlog from the holidays.

**Comment by RamIdeas** [comment] 2016-01-08 11:58
Getting the exact same error and stack trace using node v4.2.4 and v5.4 on Windows Server 2012

**Comment by mcorb** [comment] 2016-01-09 03:07
Maybe ursa didn't install because of a missing build environment.

Setting up a build environment (apt-get install build-essential) and doing npm install from scratch gets ursa installed and used instead of forge.

Unfortunately a similar error happens with ursa (different error message, but again relating to an unexpected condition).

My two cents: the real problem here seems to be lack of error reporting. If the error message specified the exact server-client operation which failed, it'd be easier for the community to help out and delegate bug reports to the appropriate module or check the letsencrypt changelog instead of blocking on @coolaj86 (whose efforts are totally appreciated).

**Comment by rmhrisk** [comment] 2016-01-09 05:30
Maybe, but build enviroments dont really belong on production boxes either. @coolaj86 I have a WebCrypto PolyFill for Node based on OpenSSL. I will be releasing this as MIT soon, it is usable as is though. Let me know if you want this instead.

**Comment by skelly-jbfc** [comment] 2016-01-14 16:56
Just want to let you know I've run into this issue as well on a Windows 7 64-bit machine. Exact same error.

**Comment by navossoc** [comment] 2016-01-16 03:50
Same here.

Windows Server 2012 x64 and Node.js 4.2.4

**Comment by hansjd** [comment] 2016-02-06 16:08
same issue here...
node 5.5.0
npm 3.3.12
windows 10 pro 64bit

when doing npm install -g letsencrypt-cli
I get 
```
> ursa@0.9.1 install C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa
> node-gyp rebuild

C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  asprintf.cc
..\src\ursaNative.cc(166): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(181): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(388): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(389): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(696): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(744): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(789): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(836): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(955): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1013): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\ursaNative.vcxproj]
  win_delay_load_hook.c
     Creating library C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\Release\ursaNative.lib and object C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\Release\ursaNative.exp
  Generating code
  Finished generating code
  ursaNative.vcxproj -> C:\Users\hansjd\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\ursa\build\Release\\ursaNative.node
```

**Comment by jsumners** [comment] 2016-02-20 00:09
Using node 4.3.1 I'm getting this issue. I explicitly installed with `--no-optional` because I do not want to compile anything (or have to install compilers on my web server). Can we get a resolution to this?

**Comment by knight00931** [comment] 2016-02-20 10:06
If you encountered the error `[Error]: letsencrypt-cli
TypeError: must start with number, buffer, array or string`

Just delete or rename the folders 'accounts' and 'renewal' in config dir and run again. Works on my Win10 x64, Node js 5.6.0 and latest letsencrypt-cli.

Be careful don't hit the rate limit like me...

**Comment by coolaj86** [comment] 2016-02-22 16:39
Oops, I forgot to publish the new version... just a sec...

**Comment by coolaj86** [comment] 2016-02-22 16:42
This should be resolved in v1.0.8.

I think I fixed it in `node-letsencrypt` a while ago, but this package was still using `v1.3.0` and we're now at `v1.4.3`.

Let me know if it's still an issue.

**Comment by jsumners** [comment] 2016-02-24 04:25
I'll be giving it a go soon. Hopefully before the weekend.

**Comment by scytalezero** [comment] 2016-02-26 19:53
I'm having this same problem on Windows Server 2012R2 x64. I'm on the latest version of letsencrypt-cli and it is using node-letsencrypt 1.4.3. Deleting the "accounts" and "renewal" folders makes it work for me, so for now I've just added the deletion to my scheduled task.

**Comment by mahmalsami** [comment] 2016-02-27 12:20
just update from v1.0.7 to v1.0.8 -> still facing the same issue.
This should make the error disappear:
```
rm -r ~/letsencrypt/etc/renewal/
rm -r ~/letsencrypt/etc/accounts/
```

**Comment by jsumners** [comment] 2016-02-29 01:19
I was just able to test the fix. It is working great. Thank you.

**Comment by PhilippCh** [comment] 2016-03-21 18:01
Would be great if you could fix this!

**Comment by andrewmcwatters** [comment] 2016-04-22 20:09
Any news on this?

**Comment by coolaj86** [comment] 2016-04-22 20:19
Is anyone still having this problem on Linux? Or is it just a Windows problem?

I finally got a Windows computer yesterday, so I should be able to test this now.

**Comment by coolaj86** [comment] 2016-04-22 20:19
@rmhrisk I'd love a pull request for that polyfill. This is where it would need to go: https://github.com/Daplie/letiny-core/blob/master/lib/node.js

**Comment by andrewmcwatters** [comment] 2016-04-22 20:32
I actually had this issue on Linux. :( Same stack trace, more or less. I'm actually being hit by this in `letsencrypt-express`, though. I happened to see the same issue here, and figured it's coming from here or the library.

**Comment by coolaj86** [comment] 2016-04-22 21:28
I'm moving this over to https://github.com/Daplie/node-letsencrypt/issues/23 and closing from this repo.

**Comment by coolaj86** [comment] 2016-04-22 21:31
I've got some renewals to do myself, so hopefully I can reproduce and fix it over the weekend.

**Comment by Bluejay47** [comment] 2016-05-20 04:31
Not sure where you are at with this, but I am still getting the same error on Window 10 64 bit. Deleting the config directories removed the error.

**Comment by jsumners** [comment] 2016-05-25 17:52
If you guys are just needing a tool that isn't a ridiculous to setup and use as the official one, I just found this -- https://github.com/hlandau/acme . It works *great*.

**Comment by scytalezero** [comment] 2016-05-25 19:59
Acme looks cool but there's no Windows support. That's the whole reason I looked for a Node solution in the first place.

**Comment by andrewmcwatters** [comment] 2016-05-25 20:15
`auto-sni`

**Comment by coolaj86** [comment] 2016-08-10 02:49
This is fixed in v2.0.0, which was just published.
https://github.com/Daplie/letsencrypt-cli

**Closed by coolaj86** 2016-08-10 02:49 UTC

**Comment by coolaj86** [comment] 2016-08-10 02:51
Also, Windows is now supported.

(note to self: update letsencrypt-express and close https://github.com/Daplie/letsencrypt-express/issues/45)

**Comment by scytalezero** [comment] 2016-08-10 14:21
Thanks for the hard work on this issue!
